import type { PropsWithChildren } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { colors } from "./theme";
export function Screen({ children }: PropsWithChildren) { return <View style={s.screen}>{children}</View>; }
export function Card({ children }: PropsWithChildren) { return <View style={s.card}>{children}</View>; }
export function Title({ children, subtitle }: PropsWithChildren<{ subtitle?: string }>) { return <View style={s.titleBox}><Text style={s.title}>{children}</Text>{subtitle ? <Text style={s.subtitle}>{subtitle}</Text> : null}</View>; }
export function Button({ title, onPress, disabled, secondary }: { title: string; onPress(): void; disabled?: boolean; secondary?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button, secondary && s.secondary, disabled && s.disabled]}><Text style={[s.buttonText, secondary && s.secondaryText]}>{title}</Text></Pressable>; }
export function State({ loading, error }: { loading: boolean; error?: string | null }) { return loading ? <ActivityIndicator color={colors.coral} /> : error ? <Text style={s.error}>{error}</Text> : null; }
export const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background, padding: 18, gap: 14 }, card: { backgroundColor: colors.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: colors.border, gap: 10 }, titleBox: { gap: 2, marginBottom: 4 }, title: { fontSize: 29, fontWeight: "800", color: colors.ink }, subtitle: { fontSize: 15, color: colors.muted }, button: { backgroundColor: colors.coral, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 12, alignItems: "center" }, secondary: { backgroundColor: colors.coralSoft }, disabled: { opacity: .45 }, buttonText: { color: "white", fontWeight: "800" }, secondaryText: { color: colors.ink }, error: { color: colors.warning }, row: { flexDirection: "row", gap: 10, alignItems: "center" }, label: { color: colors.ink, fontSize: 17, fontWeight: "700" }, meta: { color: colors.muted } });
